services:
  - redis-server
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
  - "sudo apt-get update"
  - "sudo apt-get install mongodb-org-server"
  - "sudo apt-get install -y git build-essential"
  - "git clone -b v1.x.x https://github.com/NodeBB/NodeBB.git nodebb"
  - cd nodebb
  - npm i --production
  - database=mongo node app --setup
  - cd ..
before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
branches:
  only:
    - master
